sudo: required
services:
  - docker
before_install:
  - docker build -t sulabh/docker-react-cicd -f Dockerfile.dev .
script:
  - docker run -e CI=true sulabh/docker-react-cicd npm run test -- --coverage
