sudo: required
services:
  - docker
before_install:
  - docker build -t sulabh/docker-react-cicd -f Dockerfile.dev .
script:
  - docker run -e CI=true sulabh/docker-react-cicd npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-cicd"
  env: "Dockerreactcicd-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-524557274175"
  bucket_path: "docker-react-cicd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
